Combining all tool usage into the same plot
Dansk-Data-Science-Community/danish-data-science-salary-survey pull request #35
Opened 2023-03-04 12:13 UTC by elgehelge

There are many ways to do this, so let's talk about whether this is the preferred way or whether there are better ways.

My approach explained: Combine the boolean "uses_*" columns into one column ("tool_usage") containing lists of categories, and then on the UI side we expand those lists, which means that each row gets expanded out into multiple rows. This should of course _only_ happen when the "tool_usage" option has been chosen.

![image](https://user-images.githubusercontent.com/665484/222900148-79d5bfe3-c1eb-41c3-8307-02da7a337f28.png)

2023-03-13 10:40 UTC, saattrupdan requested changes
Just added a few comments to clarify what's going on. Code looks good 😊

2023-03-13 10:40 UTC, saattrupdan commented on src/dashboard.py
> +            df = df.explode(option)
```suggestion
        # The features in `MULTI_CATEGORICAL` are lists of values, so we turn explode the feature to split
        # a row with values `[a, b]` into two rows with values `a` and `b`. This allows us to compute the counts
        # properly for the plot
        if option in MULTI_CATEGORICAL:
            df = df.explode(option)
```

2023-03-13 10:40 UTC, saattrupdan commented on src/data.py
> +    df["tool_usage"] = df["tools"].str.split(";")
```suggestion
    # Add a newline in all the `tools` strings, to make it look prettier on the plot
    df["tools"] = df["tools"].str.replace("(e.g.", "\n(e.g.", regex=False)
    
    # Create a `tool_usage` feature, being lists of tools.
    df["tool_usage"] = df["tools"].str.split(";")
```

2023-03-27 19:46 UTC, elgehelge commented
Thanks, @saattrupdan! Definitely better with some good comments

2023-03-27 22:29 UTC, elgehelge commented
Finally 😅 @saattrupdan

2023-03-30 12:42 UTC, saattrupdan approved these changes
LGTM! 🙂

2023-04-02 20:01 UTC, merged